Skip to content
This repository
Search
Pull requests
Issues
Gist
 @fabriziomarmitt
 Sign out
 Watch 13
  Star 102
 Fork 142 spring-cloud-samples/configserver
 Code  Issues 2  Pull requests 0  Projects 0  Wiki  Pulse  Graphs
Branch: master Find file Copy pathconfigserver/src/main/resources/application.yml
614b650  on 5 Apr 2016
@spencergibb spencergibb polish
2 contributors @dsyer @spencergibb
RawBlameHistory     
38 lines (31 sloc)  764 Bytes
server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help